### ISSUE TITLE
Hiding Input

### ISSUE THREAD

**Issue by r0f1** [dexplo/dataframe_image#10]
Hi, love your package. Is there maybe a possibility to hide the input cells? For example, when I am using `jupyter nbconvert` I would use it with these flags: ```jupyter nbconvert notebook.ipynb --to pdf --no-input --no-prompt --output result.pdf```. So are there flags available equivalent to these ones?

**Comment by MichaelSainsburys** [comment]
Would be great to see a response to this soon

**Comment by Francoisgoujon** [comment]
Hello! I would need this behavior as well, did you guys found a way to hide the code ?
I only recently discovered dataframe_image which is already very usefull, but such an option would make it really better.

**Comment by PaleNeutron** [comment]
@Francoisgoujon , option is added in latest commit [fc98335](https://github.com/dexplo/dataframe_image/commit/fc9833565c643310e8c042c4c03e1b170e9eea00) and will release soon.

**Comment by Francoisgoujon** [comment]
@PaleNeutron oh that’s great, thanks a lot !
Do you have an idea of when it should be released ? Thanks

**Comment by PaleNeutron** [comment]
Try the latest release https://github.com/dexplo/dataframe_image/releases/tag/v0.1.12

**Comment by Francoisgoujon** [comment]
Thank you very much! You’re a boss!

**Comment by r0f1** [comment]
Thank you. I just installed it and can confirm that adding ` --no-input=true` to the command line arguments does work :)

**Comment by Francoisgoujon** [comment]
Hello,
I made some tries and while it works perfectly when using use="latex", it does not seem to work when using use="browser". 

I tried to understand the reason for that but I am not sure:
- When using "latex", it calls to_pdf_latex which is using PDFExporter of nbconvert, which is itself based on Exporter of nbconvet. 
- When using "browser", it calls to_pdf_browser which is using BrowserExporter which is directly based on Exporter of nbconvert. 
- The only difference is that with latex, you add to the config: "NbConvertBase": {"display_data_priority": self.DISPLAY_DATA_PRIORITY}, but I don’t see why it would be linked. 

Do you have an idea why it won’t work with use="browser" and if yes, is it a quick fix ?
Thanks for your help again.

**Comment by PaleNeutron** [comment]
No, I think it is because `--no-input` is translate to `TemplateExporter`'s property:

```
        if no_input:
            self.nbconvert_config.update(
                {
                    "TemplateExporter": {
                        "exclude_output_prompt": True,
                        "exclude_input": True,
                        "exclude_input_prompt": True,
                    }
                }
            )
```

But I forget `BrowserExporter` is inherit from `Exporter`, so this config will not work. I'll test if everything works with `class BrowserExporter(TemplateExporter):`

**Comment by PaleNeutron** [comment]
@Francoisgoujon , you could try the latest github version if your os is not windows. There is a bug on windows and I'll fix it 
 next week.

**Comment by PaleNeutron** [comment]
@Francoisgoujon , I release a new version and should resolve browser_pdf method problem and can work in windows https://github.com/dexplo/dataframe_image/releases/tag/v0.1.13

**Comment by Francoisgoujon** [comment]
@PaleNeutron Hello, thanks again for your help on this. I installed the new version and I still have the same issue, no-input works when using latex but not browser. It does not raise any issue, it just outputs the pdf as if no-input was False. I tried on both Linux and Windows OS. Did it work on your side ? Could it be a missing dependency ?

Thanks for help.

**Comment by PaleNeutron** [comment]
@Francoisgoujon , I'm sure it works this time. Just try it.

**Comment by Francoisgoujon** [comment]
@PaleNeutron Hello! I tried on Windows and a linux server and it worked perfectly on both! Thanks a lot for the help, you’re a boss. Issue can now be closed :)
Best wishes
