### ISSUE TITLE
df.style.background_gradient() changes display of float value

### ISSUE THREAD

**Issue by yazhinia** [dexplo/dataframe_image#104]
Hi,
   Thanks for creating a useful package. I wanted to save a table content as an image. The table contains float values for example 0.2 which changes to 0.200000 upon using `style.background_gradient()`. This is not technically wrong but for visual image, the simple form of 0.2 looks better. Any effort on this aspect is much appreciated.

Thank you.

**Comment by PaleNeutron** [comment]
Please review your dataframe in notebook. It should have `0.200000` in notebook display.

<img width="933" alt="image" src="https://github.com/dexplo/dataframe_image/assets/8296331/16a86316-3372-48f7-bded-567951686b69">

-----

If you want less 0, you could try:

<img width="705" alt="image" src="https://github.com/dexplo/dataframe_image/assets/8296331/ad0c346a-02a9-4130-8374-d61a2ec387ad">

Or other methods to modify pandas styler.
