### ISSUE TITLE
No module named 'dataframe_image' 

### ISSUE THREAD

**Issue by Heroeskeeper** [dexplo/dataframe_image#107]
Doesn't work in pycharm even after installing in pycharm terminal.

**Comment by PaleNeutron** [comment]
Take care of your interpreter of debug/running settings.

![image](https://github.com/dexplo/dataframe_image/assets/8296331/86d46547-420e-44f1-98a8-de242b33f891)

It may not the same as interpreter choosed for your project.

I'm sure it's not a problem with this package.
