### ISSUE TITLE
deprecated styler render

### ISSUE THREAD

**Issue by pressplay21** [dexplo/dataframe_image#109]
dataframe version 1.4 removed the render() function. 

python3.11/site-packages/dataframe_image/_pandas_accessor.py:69

obj.render()

Change to Styler.to_html() ???

https://pandas.pydata.org/docs/whatsnew/v1.4.0.html

Deprecated Styler.render() in favor of [Styler.to_html()](https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_html.html#pandas.io.formats.style.Styler.to_html) ([GH 42140](https://github.com/pandas-dev/pandas/issues/42140))

**Comment by PaleNeutron** [comment]
Please try latest `dataframe_image` version, or just review latest code in the repo.
