### ISSUE TITLE
Saving as SVG using matplotlib backend

### ISSUE THREAD

**Issue by ljmartin** [dexplo/dataframe_image#11]
Hi,
Love this library and it solves a problem I've had for a while, so thank you!

I'd like to be able to save to `.svg` with the matplotlib backend, due to resolution/filesize issues with `.png`. Matplotlib accepts a `format` keyword in `savefig`, i.e. `self.fig.savefig(buffer, bbox_inches=bbox, format=self.format)`.

This requires inferring the format by taking the last three letters of `filename` in `_pandas_accessor.py`, i.e. `converter = TableMaker(fontsize=fontsize, encode_base64=False, for_document=False, format=filename[-3:]).run`. That seems errorprone but I just thought I'd mention the need and reasons for saving to svg :) 

Thanks for your time!

**Comment by ljmartin** [comment]
PS - it just occurred to me that the TableMaker class could be hacked to write an SVG file directly - since it just writes rectangles, text, and lines using matplotlib anyway.

I'll have a go at it myself - let me know if it's of interest.

**Comment by PaleNeutron** [comment]
Export svg is implemented now:

```
        dstyle = df.style.background_gradient()
        dfi.export(
            dstyle, f"tests/test_output/covid19_styled.svg", table_conversion="matplotlib", dpi=100
        )
```
