### ISSUE TITLE
In latest version, figure size is too big even if I use "dpi=800, fontsize=3.8"

### ISSUE THREAD

**Issue by yun881201** [dexplo/dataframe_image#110]
Hello.
I recently reinstalled dataframe-image. 
However, unlike before, even if "dpi=800, fontsize=3.8" code is used, the image size cannot be reduced while maintaining good image quality.
How can I do this?

**Comment by PaleNeutron** [comment]
Can you provide a minimal reproduce example?

**Comment by PaleNeutron** [comment]
High dpi and very small fontsize is used in early version which adopt a bug in Chrome version 111.  And I have tried your code with version `0.1.12` it looks like the same.

I think you should export image with dpi 300 and resize it as documented in https://jupyterbook.org/en/stable/content/figures.html

**Comment by yun881201** [comment]
Unfortunately, I have a lot of dataframes which can have a different shape depending on data. Additionally, because image scaling is applied based on the container size rather than the original image size, it must be modified individually for every dataframe. It would be nice to be able to extract good quality dataframe images with a actual dataframe size in the notebook so that image scaling is not necessary.
