### ISSUE TITLE
Styled dataframe limited to 25 rows of output?

### ISSUE THREAD

**Issue by justinclarkhome** [dexplo/dataframe_image#115]
Hello! This library is very useful for me, so I thank you for that!

One thing I've noticed recently - which I suspect is cropping up through an updated dependency as it didn't happen prior to the last few days - is that **dfi.export()** seems to limit output to about 25 rows of data.

I created a fresh pip venv with dataframe_image 0.2.4, pandas 2.2.2, numpy 2.1., jupyterlab 4.2.4, matplotlib 3.9.2.

Here's a simple example, which creates a styled dataframe containing 50 random floats in a single column:

```python
import pandas as pd
import numpy as np
import io
import dataframe_image as dfi
import matplotlib.pyplot as plt

fig = plt.Figure()
random_data = pd.Series(data=np.random.normal(size=50)) \
    .to_frame('Hi').style.format('{:.2f}')
with open('test.png', 'wb') as write_obj:
    dfi.export(
        random_data,
        write_obj,
        max_rows=-1, # I tried None, -1 and 100
        dpi=None,
    )
    fig.savefig(write_obj)
```

For me, this gives the following output (only outputs 25 of the 50 rows):

![test](https://github.com/user-attachments/assets/9ec8c7f9-7736-4fb4-bea0-f4fb6e609c80)

Any ideas what may be the cause here?

Thank you!

**Comment by justinclarkhome** [comment]
Did some more digging, and I think this may be related to an update of Chrome/Chromium. I have a machine at my office with an older Chrome install that ran the above snippet cleanly (incidentally, shortly after that it had a browser update pushed, after which the output became truncated).

If anyone else is having similar issues, I was able to get similar output (ish) after installing Playwright and using that for table conversion.

**Comment by justinclarkhome** [comment]
Here is an interesting test where I pass a dataframe of 50x10 random floats into dfi.export() using chrome and playwright as the table_conversion args. 

```python
import pandas as pd
import numpy as np
import io
import dataframe_image as dfi
from PIL import Image

random_data = pd.DataFrame(data=np.random.normal(size=(50, 10))).style.format('{:.2f}')

for table_conversion in ['chrome', 'playwright']:
    with io.BytesIO() as write_obj:
        dfi.export(
            random_data,
            write_obj,
            table_conversion=table_conversion,
        )
        image_w, image_h = Image.open(write_obj).size
        print(f'{table_conversion} w x h: {image_w} x {image_h}')
```

Notice that the resulting image height from the chrome export is about half the size of the playwright export:

<img width="342" alt="Screenshot 2024-08-29 at 3 00 31 PM" src="https://github.com/user-attachments/assets/dad9424b-982e-4668-8eae-1fe9139eb86a">

**Comment by PaleNeutron** [comment]
@justinclarkhome there are two problems:

1. > At some point in the future, --headless=old will be removed and users will be expected to use a separate chrome-headless-shell binary, which [is already available](https://developer.chrome.com/blog/chrome-headless-shell).

    That means `--headless=old` is deprecated and may cause panic in the feature.
2. See https://github.com/dexplo/dataframe_image/issues/78 , we enforce `--headless=new` to make `--window-size` parameter works

It seems we need another solution.

**Comment by justinclarkhome** [comment]
Thank you @PaleNeutron. I’m just hacking that change in locally, hoping whatever happened with Chrome is fixed in a future update (allowing “new” headless to output the same as “old”). Unfortunately, I can’t download that binary in my work environment.

In the meantime I am converting my own tool to optionally use playwright, and that works, but leads to another (unrelated) issue for me that I’m trying to work out.

**Comment by PaleNeutron** [comment]
Fixed in https://github.com/dexplo/dataframe_image/releases/tag/v0.2.5

**Comment by allweathermacro** [comment]
Hi guys, i tried using playwrite, but i got other issues not related that I will need to fix. id rather stick to using chrome, you mid please guide me what is the solution i can follow to allow me to continue to use chrome. I had this issue now for 2 months that i haven't manage to solve. PaleNeutron, you mentioned Fixed  above, you mind guide me what you mean?
