### ISSUE TITLE
Export styled dataframe to png not working with matplotlib

### ISSUE THREAD

**Issue by MetaHG** [dexplo/dataframe_image#13]
Hello,

I have run the following example code to export a dataframe to a png, using the "matplotlib" table converter.

```python
import dataframe_image as dfi
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(6, 4))
df_styled = df.style.background_gradient()
dfi.export(df_styled, 'df_styled.png', table_conversion='matplotlib')
```

The image is exported without errors (only a warning about the helvetica font not being found). However, when opening the image afterwards, the style of the dataframe has disappeared and a simple dataframe without colors is displayed.
On the other hand, when using "chrome" as a table converter, the dataframe is correctly exported with its style.
Sadly, in the environement in which I am working, chrome is not available and I can't install it there, so this is not an option.

Is this the "expected" behavior when using matplotlib, or should it work like with chrome, i.e. export dataframe colors too?

**Comment by rgranit** [comment]
+1

**Comment by albantor30** [comment]
Same behaviour here : I do apply a custom style to make some cells bold, but this does not render in the png

**Comment by DaisyLL** [comment]
have same case here. have you got any solution to it?

**Comment by DaisyLL** [comment]
@tdpetrou HI sorry to trouble you. Have you got the porblem same with us .
 Export styled dataframe to png not working with matplotlib

**Comment by doogfood-snap** [comment]
+1

**Comment by paluigi** [comment]
Same problem here. Using the library on Google Colab, with the Matplotlib convertre all formatting is lost.

**Comment by Aks1623** [comment]
Same

**Comment by srini047** [comment]
Same issue here as well. Working on a data notebook platform and only the un-styled matplotlib converter working.

**Comment by kmyqchy** [comment]
+1

**Comment by yamiyukiharu** [comment]
Im having the same problem as well

**Comment by Renfle91** [comment]
+1

**Comment by PaleNeutron** [comment]
I'll diagnose it later, but it seems a limitation of `matplotlib`.

**Comment by peanutbutter97** [comment]
Hi guys, Any updates for the export styled data frame using matplotlib table conversion?

**Comment by valerianrossigneux** [comment]
Hi @PaleNeutron - any update on that ?

**Comment by paulhybryant** [comment]
Run into this problem as well

**Comment by agftrading** [comment]
Deploying a styled dataframe object using chrome table converter does not work here; produces an image, but only a thin strip of what looks like the very top of the expected image.  Deploying the matplotlib table converter does produce an image, but has similar issues to those described above; specifically colour stying disappears.

**Comment by PaleNeutron** [comment]
Supported now!

**Comment by paulhybryant** [comment]
Nice! Thanks a lot. Is it released?

**Comment by PaleNeutron** [comment]
@paulhybryant Already released.

**Comment by paulhybryant** [comment]
Thanks!
