### ISSUE TITLE
How to disable image cropping with table_conversion="chrome"

### ISSUE THREAD

**Issue by chokosabe** [dexplo/dataframe_image#16]
Hi, many thanks for this library. Came across an issue where setting the table conversion to chrome seems to come out with a third of what should be the full image. Switching the table conversion to matplotlib returns the right image but devoid of all styling. Is there a flag we might be able to use to stop the cropping?

Thanks

**Comment by Renfle91** [comment]
Hi, I have a similar issue. The table I export as an image crop at the bottom of the image. If somebody can help with this issue.

Thank you.

**Comment by muupan** [comment]
I am facing the same issue. I was able to work around the issue by setting the color of dataframe cells to a non-white color.

**Comment by PaleNeutron** [comment]
I is a breaking change with Chrome and can be fixed by latest version
