### ISSUE TITLE
Dataframe as PNG object

### ISSUE THREAD

**Issue by itang1** [dexplo/dataframe_image#19]
Can we get the ability to return the styled Dataframe as a PNG object, without needing to save the image?

Even though dfi.export() is currently broken with respect to several situations (including on Google Colab), once I have the image object, I can use other means to save it. 

This would address several issues, including #6 #7 #9 #13 #15

**Comment by znstrider** [comment]
Seconded, exporting the image into buffer / loading it into an array would be great, because that would allow us to show that image with plotting libraries like matplotlib.

**Comment by mvinoba** [comment]
Is there any workaround for this issue?

**Comment by kampelmuehler** [comment]
The only "workaround" is to save the image to disk temporarily.

**Comment by LiZhongyangLi** [comment]
You can feed it to a `BytesIO` object and show it in jupyter with `Image` from `Ipython.display`

**Comment by andrewqho** [comment]
@LiZhongyangLi I'm confused how that helps with downloading the styled object as a PNG file if all we're doing is displaying it

**Comment by JoeTinnySpace** [comment]
Any update on this? Would be handy to have the image as an object

**Comment by PaleNeutron** [comment]
It is easy and not related to this package. Just use `io.BytesIO` instead of filename.

```Python
import pandas as pd
import numpy as np
from io import BytesIO
import dataframe_image

bio = BytesIO()
df = pd.DataFrame(np.random.randint(0, 100, size=(30, 20)))
df.dfi.export(bio)
bytes = bio.read()
# do whatever you want
```
