### ISSUE TITLE
  nbconvert failed: module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by jansenicus** [dexplo/dataframe_image#2]
when downloading the result from
```
File -> Download as -> PDF - Dataframe as image (from browser) .pdf
```
running smoothly in `Python 3.8` environment but raising an error in a `Python 3.6` environment
```
  nbconvert failed: module 'asyncio' has no attribute 'run'
```
Reason: 
The `asyncio.run()` function was added in Python `3.7`.

**Comment by tdpetrou** [comment]
Thanks very much for reporting this! I'm new to asyncio, so wasn't aware of this.

**Comment by tdpetrou** [comment]
This should be fixed in the new version. I copied and pasted the code for `run` from 3.7 into a separate module within dataframe_image
