### ISSUE TITLE
Export just a DataFrame - not just the whole notebook

### ISSUE THREAD

**Issue by chris1610** [dexplo/dataframe_image#3]
Really useful package. It works well for me. One thing I would be interested in doing is exporting just the Dataframe - not the entire notebook. Is that a potential option or is that way outside the scope of this project?

Thanks again for the package.

**Comment by tdpetrou** [comment]
That's definitely in scope and something I've been meaning to add to it. I have a pretty big update coming with the next release of this package.

I could probably add it using the register api. Let me experiment and update what I come up with here.

**Comment by tdpetrou** [comment]
Just added this functionality and it will be in the next release. Great idea! And thanks for tuning me into pandas accessor API. 

Here's the link for anyone who randomly stumbles upon this issue - https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.register_dataframe_accessor.html
