### ISSUE TITLE
Script being killed after "multiple threads in process gpu-process" message

### ISSUE THREAD

**Issue by nexbelgium** [dexplo/dataframe_image#33]
Hi, 

I have a script which creates a dataframe and generates a PNG file using dfi.export(). I ran it for a year on a raspberry pi and it never failed once. Now, I run it on a Ubuntu VPS and it works 90%-95% of the time. Sometimes the process just gets killed.  It has the same amount of RAM as the raspberry I was using.

When running the code, I get following messages:
```
[0105/163538.099004:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[0105/163538.352526:INFO:headless_shell.cc(653)] Written to file /tmp/tmp35i6n8rc/temp.png.
```

So I guess it has something to do with the memory usage of the GPU. But for that single small images, it seems strange that it takes up all the memory. How can we disable the use of the GPU? 

Or are there any other solutions I can apply not to receive these messages?

**Comment by tdpetrou** [comment]
Thanks for using this package. I haven't looked at this package in a long while, but I would look into headless chromium options. There might be one that does not use the GPU.

**Comment by nexbelgium** [comment]
Thanks for your reply, I have already looked into this solution, but how do I make dfi.export() run something like `google-chrome-stable --headless --disable-gpu` ?

**Comment by tdpetrou** [comment]
The call to headless chrome is here https://github.com/dexplo/dataframe_image/blob/master/dataframe_image/_screenshot.py#L90

But, the `--disable-gpu` option is already set.

**Comment by nexbelgium** [comment]
Yes, I had seen that in the code, so it's strange that I get this message about gpu-process. Maybe it has something to do with a sandbox mode? Should we add --no-sandbox?

**Comment by nexbelgium** [comment]
I could solve the problem by downgrading Chrome to version 88. More recent versions each rise different kind of errors.

**Comment by Rabelaiss** [comment]
> I could solve the problem by downgrading Chrome to version 88. More recent versions each rise different kind of errors.

Where did you download version 88 from?
I tried
`sudo wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_88.0.4324.96-1_amd64.deb`
but it says error 404 not found

**Comment by nexbelgium** [comment]
I did the following:
`wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_**88.0.4324.182-1_**amd64.deb"
sudo dpkg -i "google-chrome-stable_**88.0.4324.182-1_**amd64.deb"
rm -i "google-chrome-stable_**88.0.4324.182-1**_amd64.deb"`

**Comment by Rabelaiss** [comment]
@nexbelgium also that one raise error 404 not found

**Comment by nexbelgium** [comment]
It was some time ago, maybe it's not available anymore.

All available versions of Chrome can be found here:
https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable?id=202706&page=1
