### ISSUE TITLE
highlight based on cell value

### ISSUE THREAD

**Issue by shalli2** [dexplo/dataframe_image#40]
How to change the font color or the background color of a cell of a certain column if the value is >= of some number? Thank you.

**Comment by Bhuvneshwar-Vishwakarma** [comment]
def color_row(cell_value):
        if cell_value >= num:
                return 'color: %s' % red
        else:
                return 'color: %s' % green
df = df.style.applymap(get_color, subset=['column_name'])


# for font color :      return 'color: %s' % color_name
# for background color :        return 'background-color: %s' % color_name
