### ISSUE TITLE
Superscript text not exported properly

### ISSUE THREAD

**Issue by moyscode** [dexplo/dataframe_image#42]
I have a data-frame with some Superscript text crate with the code `[cm\N{SUPERSCRIPT THREE}/min]` .
![grafik](https://user-images.githubusercontent.com/92194668/172325794-872ca5b8-e90e-4315-9258-0c3c90cf0451.png)

However when i export this df as a image with the code below.
```
import dataframe_image as dfi
dfi.export(styled_df, "resultTable.png"))
```
It does not get exported properly (pic below). There a weird straight line like character instead of Superscript
![grafik](https://user-images.githubusercontent.com/92194668/172325895-cbb3cadc-2353-42fa-89a7-0819d08b53c9.png)

Is there workaround for this?

**Comment by moyscode** [comment]
I did that too with `[cm\u00b3/min]` instead of `[cm\N{SUPERSCRIPT THREE}/min]`. Even with this approach, the table looks correct in Jupyter notebook but after saving it as .png with `dataframe_image`, the same  weird straight line like character is there instead of Superscript.

**Comment by moyscode** [comment]
Same result even with character ³. The same weird straight line like character is there instead of Superscript in the exported .png file.

**Comment by moyscode** [comment]
Any fix or workaround for this issue?

**Comment by moyscode** [comment]
Any fix or workaround for this issue?

**Comment by PaleNeutron** [comment]
```python
converters = ["chrome", "selenium", "matplotlib", "html2image", "playwright"]
for c in converters:
    df_latex = pd.DataFrame(["cm³/mm²"])
    dfi.export(
        df_latex,
        f"c.png",
        table_conversion=c,
    )
```
Following 5 images are test result. I can not reproduce the bug.

![test_superscript chrome](https://github.com/dexplo/dataframe_image/assets/8296331/a848de57-d885-4a75-80bc-0fbcd6977c74)
![test_superscript playwright](https://github.com/dexplo/dataframe_image/assets/8296331/d363282e-1c2a-4881-821f-2026226c6d82)
![test_superscript html2image](https://github.com/dexplo/dataframe_image/assets/8296331/202bd6e5-9efa-40e0-97b4-ef412fffa525)
![test_superscript matplotlib](https://github.com/dexplo/dataframe_image/assets/8296331/afdbbf6a-682b-46fa-ae1d-01b1d0199963)
![test_superscript selenium](https://github.com/dexplo/dataframe_image/assets/8296331/7df7a93a-a96f-4ae3-a62e-a85d4b9d006b)
