### ISSUE TITLE
Save to remote file system

### ISSUE THREAD

**Issue by ajmeese7** [dexplo/dataframe_image#43]
Hey there, quick question that I am trying to help someone with. They are looking to save their `dif`-generated image directly to an S3 bucket on AWS without saving the image locally. Do you know of any ways to specify this currently with the library?

**Comment by ajmeese7** [comment]
@PaleNeutron do you have an example of how to convert the image generated by this library to `BytesIO` without saving it to the disk? That would be greatly appreciated!

**Comment by PaleNeutron** [comment]
```python
import pandas as pd
import numpy as np
import dataframe_image as dfi
from io import BytesIO
```


```python
df = pd.DataFrame(np.random.rand(5,8))
```


```python
df
```




<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.018129</td>
      <td>0.511246</td>
      <td>0.210085</td>
      <td>0.174160</td>
      <td>0.562191</td>
      <td>0.533760</td>
      <td>0.836536</td>
      <td>0.058780</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.452144</td>
      <td>0.718135</td>
      <td>0.350870</td>
      <td>0.881881</td>
      <td>0.708918</td>
      <td>0.990391</td>
      <td>0.864563</td>
      <td>0.440264</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.154236</td>
      <td>0.069712</td>
      <td>0.580959</td>
      <td>0.170795</td>
      <td>0.621348</td>
      <td>0.202536</td>
      <td>0.964883</td>
      <td>0.566463</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.373485</td>
      <td>0.480376</td>
      <td>0.956419</td>
      <td>0.230610</td>
      <td>0.386035</td>
      <td>0.750750</td>
      <td>0.437797</td>
      <td>0.030412</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.001774</td>
      <td>0.984068</td>
      <td>0.421984</td>
      <td>0.026590</td>
      <td>0.665637</td>
      <td>0.395694</td>
      <td>0.141108</td>
      <td>0.537476</td>
    </tr>
  </tbody>
</table>
</div>




```python
png_io = BytesIO()
df.dfi.export(png_io)
```


```python
data = png_io.getbuffer()
```


```python
len(data)
```




    33341




```python
type(data)
```




    memoryview

**Comment by ajmeese7** [comment]
You're the best, thanks for your help!
