### ISSUE TITLE
Round to two decimal places

### ISSUE THREAD

**Issue by antonkurtis** [dexplo/dataframe_image#44]
How can I round to two decimal places all numbers in DF?
Now use this:
    df_styled = df.style.background_gradient()
    dfi.export(df_styled, "adv.png")
Return 6 decimal places

Thank you!

**Comment by tdpetrou** [comment]
I believe you'll need to use the styler format method. See here for more details. https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.format.html
