### ISSUE TITLE
Can change font family when use matplotlib?

### ISSUE THREAD

**Issue by kmyqchy** [dexplo/dataframe_image#47]
It will be wrong when i export png. It seems that matplotlib dont have 'Helvetica' font family. Can i change it in my code? Or can choice 'sans-serif'.
At the moment I change the ‘[_matplotlib_table.py]’ by my self.

**Comment by PaleNeutron** [comment]
@kmyqchy Can you share code changed?

**Comment by kmyqchy** [comment]
> @kmyqchy你可以分享代码改变吗？

https://github.com/dexplo/dataframe_image/compare/master...kmyqchy:dataframe_image:patch-1

**Comment by PaleNeutron** [comment]
@kmyqchy It is removed now https://github.com/dexplo/dataframe_image/commit/d540f5f4f184a612b8553fbc0feeba0dc514e871 

Users could specific fonts by [rc method](https://matplotlib.org/stable/tutorials/introductory/customizing.html).

**Comment by kmyqchy** [comment]
> @kmyqchy It is removed now [d540f5f](https://github.com/dexplo/dataframe_image/commit/d540f5f4f184a612b8553fbc0feeba0dc514e871)
> 
> Users could specific fonts by [rc method](https://matplotlib.org/stable/tutorials/introductory/customizing.html).

谢啦~
