### ISSUE TITLE
Strange markdown convertion behavior

### ISSUE THREAD

**Issue by keufran** [dexplo/dataframe_image#53]
Hi,

Thanks for your work, very useful to me.

When using dataframe_image to produce a markdown conversion of my notebooks, I notice that part of the markdown result is ... html (paragraphs, sections, ...) !

I looked at the source code but I'm not familiar with the usage of nbconvert as a library. 

All I can say is that a MarkdownExporter is used but before that a MarkdownPreprocessor is called. 
If I remove it, my problem is solved.

I guess that Preprocessing of MarkDown cells is needed when rendering to latex/pdf, but I think it is unecessary when rendering to markdown.

A simple fix in convert() from _convert.py function would be (line 327 in master):
```python
if "md" not in self.to:
    MarkdownPreprocessor().preprocess(self.nb, self.resources)
```

What do you think about it ?

If you wish, I can do a PR. I have never done that before but it's an opportunity to learn :)

**Comment by PaleNeutron** [comment]
Can you upload a notebook facing this problem? so we can test it to findout the problem.

**Comment by keufran** [comment]
Sorry for the delay, but here it is.

[minimal_markdown.zip](https://github.com/dexplo/dataframe_image/files/9644134/minimal_markdown.zip)

**Comment by PaleNeutron** [comment]
@keufran , thanks for reporting this bug, it have been fix in the latest version.

Please try to install version 0.1.3 and see if the bug still exist.

**Comment by keufran** [comment]
It works, thank you !
