### ISSUE TITLE
I got the error 'Styler' object has no attribute 'dfi'

### ISSUE THREAD

**Issue by yun881201** [dexplo/dataframe_image#55]
Hello, I am using dataframe_image to save styled dataframe as PNG. But I got the error 'Styler' object has no attribute 'dfi'. This error is embarrassing, because the description of this library states that styled dataframes can also be saved.

my code is

df = df.round(2)
df = df.style.applymap(highlight_geo)
df.dfi.export('figure/xxxx.png')

, and the error is

AttributeError: 'Styler' object has no attribute 'dfi'

Oh, dfi.export(df, 'figure/xxx.png') works well. But df.dfi.export('figure/xxxx.png') does not work.

**Comment by PaleNeutron** [comment]
Thanks for reporting!

I think it works as documented, but may be a little confusing.

```
>>> df.dfi.export('df.png')
>>> df_styled.export_png('df_styled.png')
```


I suggest using functions directly from dfi.
