### ISSUE TITLE
Table size smaller when exporting 

### ISSUE THREAD

**Issue by catarinarurbano** [dexplo/dataframe_image#56]
When exported, the size of the table is always the same, regardless of the settings made for its size in the jupyter notebook (when viewing it in the Jupyter notebook it has the specified size, but when exporting it is minimal). Therefore, it is impossible to see the letters and what is written with many rows and few columns.

**Comment by PaleNeutron** [comment]
Can you attach an example here?

**Comment by catarinarurbano** [comment]
Of course, when I customize the table so that it looks the way I want it, it returns as expected in the Jupyter notebook. However, when I export it, it always stays the same size, regardless of the changes I make.

<img width="611" alt="JupyterTable" src="https://user-images.githubusercontent.com/72030080/195412159-ab5f9d30-42cd-45f0-9eac-876c8feaac36.png">

![ExportedTable](https://user-images.githubusercontent.com/72030080/195412352-ef75fbd4-72a9-4ed2-9f38-fe2d29a11cdc.png)

**Comment by PaleNeutron** [comment]
You can not use `table` selector with `set_table_styles`, you should use '*' if you want to select whole table.

```python
df = pd.read_csv(
    "tests/notebooks/data/covid19.csv", parse_dates=["date"], index_col="date"
)

s1 = dict(
    selector="*",
    props=[
        ("font-family", "Source Sans Pro"),
        ("font-size", "20px"),
        ("margin", "30px auto"),
        ("border-collapse", "collapse"),
        ("border", "1px solid #eee"),
        ("border-bottom", "2px solid #00cccc"),
    ],
)

styles = [s1,dict(selector="caption", props=[("caption-side","bottom")])]

s_df = df.head(30).style.set_table_styles(styles).hide(axis='index').set_caption("test")  
s_df
```

![image](https://github.com/dexplo/dataframe_image/assets/8296331/5af64489-6908-4d91-b241-aee6812785f2)

```python
dfi.export(s_df, "s_df.png")
```
![image](https://github.com/dexplo/dataframe_image/assets/8296331/723ae884-0bc5-422a-a73c-413fd891bb99)
