### ISSUE TITLE
Add parameter for nbconvert configuration options

### ISSUE THREAD

**Issue by tdpetrou** [dexplo/dataframe_image#57]
With nbconvert, you have the option of specifying [a large number of configuration options](https://nbconvert.readthedocs.io/en/latest/config_options.html). [We even set a single config option here](https://github.com/dexplo/dataframe_image/blob/master/dataframe_image/_convert.py#L272) with `PDFExporter`. Perhaps we can add a `config` parameter, have it accept a dictionary, and forward it to `PDFExporter`. 

All of the preprocessors and exporters have config options, so I think it will be messy to try and parse all of the options. Maybe we just do PDFExporter options first?

I needed this personally to use a different latex template.

**Comment by PaleNeutron** [comment]
https://github.com/dexplo/dataframe_image/blob/0bc4c0eb2b1126e600faae6dee824778d9828cb3/dataframe_image/_convert.py#L22-L53

`nbconvert_config` configuration is available now.
