### ISSUE TITLE
Chrome executable error

### ISSUE THREAD

**Issue by imaadmkhan1** [dexplo/dataframe_image#6]
I'm running jupyter lab on a linux machine and this is the error I get while trying to export a dataframe as an image:
OSError                                   Traceback (most recent call last)
<ipython-input-63-a3b73d47a3d1> in <module>
----> 1 user_df.head().dfi.export('df.png')

~/py36/lib/python3.6/site-packages/dataframe_image/_pandas_accessor.py in export(self, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
     17                table_conversion='chrome', chrome_path=None):
     18         return _export(self._df, filename, fontsize, max_rows, max_cols, 
---> 19                        table_conversion, chrome_path)
     20 
     21 

~/py36/lib/python3.6/site-packages/dataframe_image/_pandas_accessor.py in _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
     31     if table_conversion == 'chrome':
     32         converter = Screenshot(max_rows=max_rows, max_cols=max_cols, chrome_path=chrome_path,
---> 33                                fontsize=fontsize, encode_base64=False, limit_crop=False).run
     34     else:
     35         from ._matplotlib_table import TableMaker

~/py36/lib/python3.6/site-packages/dataframe_image/_screenshot.py in __init__(self, center_df, max_rows, max_cols, chrome_path, fontsize, encode_base64, limit_crop)
     74         self.ss_width = 1400
     75         self.ss_height = 900
---> 76         self.chrome_path = get_chrome_path(chrome_path)
     77         self.css = self.get_css(fontsize)
     78         self.encode_base64 = encode_base64

~/py36/lib/python3.6/site-packages/dataframe_image/_screenshot.py in get_chrome_path(chrome_path)
     50                 if chrome_path:
     51                     return chrome_path
---> 52         raise OSError("Chrome executable not able to be found on your machine")
     53     elif system == "windows":
     54         import winreg

OSError: Chrome executable not able to be found on your machine

Any ideas how to solve this?

**Comment by VinodKumar9576** [comment]
Hi tdpetrou,

Can you direct the process for specifying the path for chrome manually?

**Comment by itang1** [comment]
I'm using google colab and ran into this as well.

Installing this helped me solve the chrome executable error: 
`!pip install chromium-chromedriver`

However, then I get a new error:
`OSError: read past end of file`


> 
> ---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> <ipython-input-8-cec243c07d6e> in <module>()
>       7 
>       8 # !pip install chromium-chromedriver
> ----> 9 df_styled.export_png('df_styled.png')
> 
> 4 frames
> /usr/local/lib/python3.7/dist-packages/dataframe_image/_pandas_accessor.py in export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
>      22 def export(obj, filename, fontsize=14, max_rows=None, max_cols=None, 
>      23                table_conversion='chrome', chrome_path=None):
> ---> 24         return _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
>      25 
>      26 
> 
> /usr/local/lib/python3.7/dist-packages/dataframe_image/_pandas_accessor.py in _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
>      71         html = obj.to_html(max_rows=max_rows, max_cols=max_cols, notebook=True)
>      72 
> ---> 73     img_str = converter(html)
>      74 
>      75     if isinstance(filename, str):
> 
> /usr/local/lib/python3.7/dist-packages/dataframe_image/_screenshot.py in run(self, html)
>     165     def run(self, html):
>     166         self.html = self.css + html
> --> 167         img = self.take_screenshot()
>     168         img_str = self.finalize_image(img)
>     169         return img_str
> 
> /usr/local/lib/python3.7/dist-packages/dataframe_image/_screenshot.py in take_screenshot(self)
>     117 
>     118         buffer = io.BytesIO(img_bytes)
> --> 119         img = mimage.imread(buffer)
>     120         return self.possibly_enlarge(img)
>     121 
> 
> /usr/local/lib/python3.7/dist-packages/matplotlib/image.py in imread(fname, format)
>    1473             return _png.read_png(fd)
>    1474     with cbook.open_file_cm(fname, "rb") as file:
> -> 1475         return _png.read_png(file)
>    1476 
>    1477 
> 
> OSError: read past end of file

**Comment by DLesmes** [comment]
I have the same error here, when importing the dataframe_image package

`OSError: Chrome executable not able to be found on your machine`

**Comment by tgdn** [comment]
I have the same issue

**Comment by crayoniq** [comment]
From: https://pypi.org/project/dataframe-image/

Using matplotlib instead of Chrome
If you do not have Chrome installed or cannot get it to work properly, you can alternatively use matplotlib to convert the DataFrames to images. Select this option by setting the table_conversion parameter to 'matplotlib'.

**Comment by adityak2920** [comment]
Try installing chrome using this:
```1. wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb```
```2. sudo apt install ./google-chrome-stable_current_amd64.deb```

**Comment by xyXiangYu** [comment]
the installation does not work for me, as I am using the company Amazon EC2 server, which is a RedHat system. I can install via python pip, but can not install other source file unless submit an application. The way that an external drive is needed is not ideal when calling a function. Also tried `table_conversion='matplotlib'`, then the format and color is partially lost (especially the color highlight is gone) when saving to an image. This leads a fact that I can not really use this package. Any idea how to fix this problem?
