### ISSUE TITLE
How to hide index when using matplotlib to convert df to image?

### ISSUE THREAD

**Issue by leonlinxs** [dexplo/dataframe_image#61]

**Comment by TahaKinik** [comment]
Have you found any solution for this ?

**Comment by hns258** [comment]
Not sure of your exact use case, but can you just hide the index in your df prior to converting using `style.hide_index()` like the following?
```
df.style.hide_index().export_png("test.png", table_conversion="matplotlib")
```
https://stackoverflow.com/questions/21256013/pandas-dataframe-hide-index-functionality

**Comment by TahaKinik** [comment]
> 

That's actually perfect thank you.
