### ISSUE TITLE
Unnecessary lines added for each page: "Loading [MathJax]/jax/output/CommonHTML/fonts/TeX/fontdata.js"

### ISSUE THREAD

**Issue by wbfw109** [dexplo/dataframe_image#66]
**Code**
![image](https://user-images.githubusercontent.com/37881026/211476441-e06abe46-66a8-4fa9-9d35-99884f529dbe.png)

**Output message**
![image](https://user-images.githubusercontent.com/37881026/211476513-c2f9749c-be8c-4dc1-a7e2-d2a546139018.png)

**Superseded last line for each page in pdf file**
![image](https://user-images.githubusercontent.com/37881026/211476376-f1e314be-1016-4d6b-a239-fcd4a3afd79c.png)

**Comment by PaleNeutron** [comment]
Can you provide a minimal test code here?

It is hard for me to reproduce it.

**Comment by wbfw109** [comment]
I'm sorry for not adding a test environment.

That code is all.
- My OS Environment is Windows 11 Version 21H2 (OS Build 22000. 1455) and I test in Ubuntu 22.04 distribution in WSL.
- Python Version: 3.11.0
- the .ipynb file includes pd.DataFrame python object from function display.display (from IPython import display)

**Comment by PaleNeutron** [comment]
Sorry but I can not reproduce it by following code (put it into ipynb by yourself):


```
import pandas as pd
import numpy as np
import dataframe_image as dfi
from IPython.display import display


df = pd.DataFrame(np.random.rand(5,10))
display(df)


dfi.convert('dfi.ipynb',
                to='pdf',
                use='latex',
                center_df=True,
                max_rows=30,
                max_cols=10,
                execute=False,
                save_notebook=False,
                limit=None,
                document_name=None,
                table_conversion='chrome',
                chrome_path=None,
                latex_command=None,
                output_dir=None,
                )

```

[dfi.pdf](https://github.com/dexplo/dataframe_image/files/10422393/dfi.pdf)

**Comment by wbfw109** [comment]
I tested again previous code. but I can not get same pdf file.
```Loading [MathJax]/jax/output/CommonHTML/fonts/TeX/fontdata.js``` does not appeared.

but output message is completely same.
---
![output](https://user-images.githubusercontent.com/37881026/211476513-c2f9749c-be8c-4dc1-a7e2-d2a546139018.png)

I don't know what's problem. but now is ok.
If there are no issues after that, I will close the issue. Thanks you for testing.
