### ISSUE TITLE
Library not working in COLAB

### ISSUE THREAD

**Issue by wosantos95** [dexplo/dataframe_image#73]
Hi,
I'm use Dataframe_image library for some time in COLAB,
and now it is following the following error:

 [Errno 2] No such file or directory: '/tmp/tmp7uvd_nzq/temp.png' , can anyone help?

tmp7uvd_nzq = TemporaryDirectory

**Import colab**

!pip install dataframe-image
!apt install chromium-chromedriver
import dataframe_image as dfi

**Comment by PaleNeutron** [comment]
I should work now following related section in readme
