### ISSUE TITLE
Chrome screenshot log now appears in PDF when executing the notebook first

### ISSUE THREAD

**Issue by tdpetrou** [dexplo/dataframe_image#75]
When choosing to execute the notebook first (either through the notebook interface or the library), the screenshot log appears in the resulting PDF. See image below.

```python
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/dexplo/dataframe_image/master/tests/notebooks/data/bikes.csv')
df
```
<img width="724" alt="Screen Shot 2023-01-24 at 7 28 29 PM" src="https://user-images.githubusercontent.com/7226751/214460009-87fa7a03-d7dd-4775-9490-8dbef94fc634.png">

It looks like it can be removed with a post processor that searches for this text, but hopefully there is a way to prevent this.

**Comment by PaleNeutron** [comment]
Seems not appeared in latest version?
