### ISSUE TITLE
matplotlib style not working

### ISSUE THREAD

**Issue by peanutbutter97** [dexplo/dataframe_image#77]
I am using table conversion "matplotlib" but it is not working

**Comment by Hypurrnating** [comment]
yeah all I need is the table to be left aligned so its actually normal.
Styling works fine with chrome but chrome is not ideal for me so idk

**Comment by valerianrossigneux** [comment]
Can matplotlib still be used and have some form of styling like cells background etc?

**Comment by PaleNeutron** [comment]
Colorful style is supported by matplotlib backend, see https://github.com/dexplo/dataframe_image/releases/tag/v0.1.11

**Comment by valerianrossigneux** [comment]
Oh splendid, overlooked that part sorry
