### ISSUE TITLE
Similar to issue #79(Problem with DataFrame_Image No such file or directory)

### ISSUE THREAD

**Issue by lunivilen** [dexplo/dataframe_image#80]
The issue #79 was closed, but the commit https://github.com/dexplo/dataframe_image/commit/5a0cd7f2c5454d3fe8bf24265b1a46e1938c0bb2 didn't solve the problem. Now the library does not create a picture at all, and on line 134 in _screenshot.py it tries to access a non-existent file

**Comment by aibanez7** [comment]
I am still having the same issue as well. 
I have tried every suggestion from issue #79 and every combination thereof, but I continue getting the same error where _sceenshot.py tires to access a non-existent file. 
I can see that the .html file is being correctly generated, but not the image file.
