### ISSUE TITLE
Wrapping long text in exported images

### ISSUE THREAD

**Issue by jonnyzwi** [dexplo/dataframe_image#83]
Is there a way to have exported DF images wrap long text?  

I am able to properly set the width property of the `styled_df` with:

`styled_df = df.style.set_properties(subset=['Long Text'], **{'width': '20em'})`

It displays properly in my notebook, but the exported DF image always results in extremely wide columns to accommodate long text—effectively ignoring the style properties that I know I set.

The result is that the exported image is not usable in my situation

Thanks for any help.

**Comment by ranpro** [comment]
@ranpro

**Comment by PaleNeutron** [comment]
@ndalchau For short, please add '\n'  manully.

```python
  df = pd.DataFrame({"My long\ncolumn name\nthat I want to wrap": [1, 2, 3, 4], "Another column": [2, 3, 4, 5]})
  styled = df.style.set_properties(subset=df.columns, **{'width': '90px'})

  dfi.export(styled, "output.png", table_conversion="matplotlib")
```
![output](https://github.com/dexplo/dataframe_image/assets/8296331/45eb329d-cc12-405e-8349-57a1ca3b18e1)

Long reason:

Current matplotlib method is just for some very simple case or user can not install any browser somehow. We get some key information from html and draw it by matplotlib not 'render' html so most css won't be supported.

For this case:

Column width in matplotlib method is calculated by

https://github.com/dexplo/dataframe_image/blob/570fe8df9fcd140fa5db98b0e244fc2e05d18647/dataframe_image/converter/matplotlib_table.py#L174-L198

You can see it is nothing with css. If we want to support all css, it will be some kind of "reimplement a webkit".

I suggest: if you only want to wrap long headers. write a function automatically add '\n' to your dataframe headers or use any browser-based convert method to get 1:1 same picture.

**Comment by ndalchau** [comment]
Thanks, that makes sense. I'll not try and use CSS with this library. I think this issue can be closed now.
