### ISSUE TITLE
Incompatibility bug within "_screenshot.py" with function "take_screenshot"

### ISSUE THREAD

**Issue by tdefise** [dexplo/dataframe_image#85]
It seems that within "_screenshot.py" in function "take_screenshot", "os.geteuid()" is used, which is not compatible for Windows-based system.

`
if os.geteuid() == 0:
    args.append("--no-sandbox")
`

![image](https://user-images.githubusercontent.com/36169753/230033767-6b44cdc8-5d72-42ba-8a1f-b67ff2b547c9.png)

**Comment by PaleNeutron** [comment]
Oops, I'll find an windows environment to test every release manually.

**Comment by tdefise** [comment]
Thanks for the quick fix @PaleNeutron
