### ISSUE TITLE
“syntaxerror: not a png file” error in dataframe_image library

### ISSUE THREAD

**Issue by rasimsahin** [dexplo/dataframe_image#87]
İ’m using Python 3.6.8, until chrome upgrade to new version I can use DFI to export styled dataframe to PNG. But after chrome upgrade , i have error like “syntaxerror: not a png file” .
I've looked through the issues but couldn't find any solution. Anyone have any ideas for a definitive solution for this?

**Comment by Madanraj-Delta** [comment]
if the columns is greater than 8, facing this problem @PaleNeutron Please check..

**Comment by Madanraj-Delta** [comment]
This is working on version 0.1.10 but having issue on version 0.1.11, the latest release is throwing the issue.

@PaleNeutron Please verify the release done on apr 23.

**Comment by PaleNeutron** [comment]
@Madanraj-Delta 

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/8296331/235037358-4954b61b-9b4a-4ac3-9bb1-c7da8ad7efad.png">

I can not reproduce any syntaxerror.
