### ISSUE TITLE
Expose a `__version__` attribute

### ISSUE THREAD

**Issue by Erotemic** [dexplo/dataframe_image#94]
It would be useful if the main `__init__.py` exposed a `__version__` attribute. While it's not required that a packge have one, it is fairly standard and a lot of tools expect it to exist. It seems the tool is currently using scm_version from setuptools-scm. Not sure what the exact right way to use this is, but modifying setup.py to include:

```
setuptools.setup(
...
    use_scm_version={
        'write_to': 'dataframe_image/_version.py',
        'write_to_template': '__version__ = "{version}"',
        'tag_regex': r'^(?P<prefix>v)?(?P<version>[^\+]+)(?P<suffix>.*)?$',
    },
...
)
```

Seems like a good starting point. Then `__init__.py` can include `from ._version import __version__`.

**Comment by PaleNeutron** [comment]
Thanks for your good idea and I'll put it into project next release.

**Comment by PaleNeutron** [comment]
Finished at https://github.com/dexplo/dataframe_image/commit/cf3351dd5179f3ed0f11868184fe848cca2d0298
