### ISSUE TITLE
Screenshot cuts upper margin if white

### ISSUE THREAD

**Issue by jsulopzs** [dexplo/dataframe_image#98]
White header:

![02_df_style png-Preview](https://github.com/dexplo/dataframe_image/assets/46565164/cf875685-67c0-4d06-bb98-3286c7957270)

Black header:

![02_df_style png-Preview](https://github.com/dexplo/dataframe_image/assets/46565164/18ce5a3c-6d62-468a-8f3b-7363b8712c04)

The Chrome screener commits the white margin because it doesn't notice the difference. I'd appreciate it if anyone could look into this and make Chrome keep the white header margin.

**Comment by PaleNeutron** [comment]
Please make sure you are using latest version. I have make a small change to relieve this problem in previous version.

**Comment by jsulopzs** [comment]
Yes sorry about it. I had installed the library with conda.

In case people will visit this issue, the following code solved it:

pip install -U dataframe-image
